error:
    internal_error: There was an issue doing that!
    invalid_arguments: Invalid arguments!

ping:
    name: Ping
    desc: Pong!
    help:
        - ping: Pong!
    response:
        one: "Ping! {0}ms"
        two: "{0}ms"
        three: "dang da ping do be at {0}ms"
        four: "WHY DO THE PING BE AT {0}MS"
        five: "who let the ping be at {0}ms"
        six: "ping ping ping ping ping ping ping ping ping {0}ms"
